service: challenge-searchmas

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JSONPLACEHOLDER_BASE_URL: ${env:JSONPLACEHOLDER_BASE_URL, 'https://jsonplaceholder.typicode.com'}

plugins:
  - serverless-offline

functions:
  syncData:
    handler: dist/handlers/syncDataHandler.syncDataHandler
    events:
      - http:
          method: post
          path: /api/sync-data
